bhanu="hi how are you"
print(bhanu.count("h"))
print(bhanu.rstrip())
print(bhanu.removesuffix("you"))
print(bhanu.removeprefix("hi"))
print(bhanu[::-1])
print(bhanu.upper())
print(bhanu.lower())
print(bhanu.split())
print(bhanu.replace("HI","BYE"))
print(bhanu.startswith("HI"))
print(bhanu.endswith("are"))
print(bhanu.find("akw"))
print(bhanu.index("hi"))